export const CHANGE_WEIGHT = 'CHANGE_WEIGHT';
export const CHANGE_TO = 'CHANGE_TO';
export const CHANGE_FROM = 'CHANGE_FROM';

export const USER_EMAIL_CHANGED = 'USER_EMAIL_CHANGED';
export const USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED';

export const ADMIN_EMAIL_CHANGED = 'ADMIN_EMAIL_CHANGED';
export const ADMIN_PASSWORD_CHANGED = 'ADMIN_PASSWORD_CHANGED';

export const REGISTER_FIRSTNAME_CHANGED = 'REGISTER_FIRSTNAME_CHANGED';
export const REGISTER_LASTNAME_CHANGED = 'REGISTER_LASTNAME_CHANGED';
export const REGISTER_EMAIL_CHANGED = 'REGISTER_EMAIL_CHANGED';
export const REGISTER_PHONE_CHANGED = 'REGISTER_PHONE_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_CONFIRM_PASSWORD_CHANGED = 'REGISTER_CONFIRM_PASSWORD_CHANGED';

export const SHOW_MAKE_ORDER_DIALOG = 'SHOW_MAKE_ORDER_DIALOG';
export const HIDE_MAKE_ORDER_DIALOG = 'HIDE_MAKE_ORDER_DIALOG';
export const SHOW_EDIT_ORDER_DIALOG = 'SHOW_EDIT_ORDER_DIALOG';
export const HIDE_EDIT_ORDER_DIALOG = 'HIDE_EDIT_ORDER_DIALOG';
export const SHOW_CHANGE_LOCATION_DIALOG = 'SHOW_CHANGE_LOCATION_DIALOG';
export const HIDE_CHANGE_LOCATION_DIALOG = 'HIDE_CHANGE_LOCATION_DIALOG';
export const SHOW_DELETE_ORDER_DIALOG = 'SHOW_DELETE_ORDER_DIALOG';
export const HIDE_DELETE_ORDER_DIALOG = 'HIDE_DELETE_ORDER_DIALOG';
export const SHOW_USER_ACTIVATION_DIALOG = 'SHOW_USER_ACTIVATION_DIALOG';
export const HIDE_USER_ACTIVATION_DIALOG = 'HIDE_USER_ACTIVATION_DIALOG';
export const SHOW_USER_PROFILE_DIALOG = 'SHOW_USER_PROFILE_DIALOG';
export const HIDE_USER_PROFILE_DIALOG = 'HIDE_USER_PROFILE_DIALOG';
export const SHOW_SPECIFIC_USER_PROFILE_DIALOG = 'SHOW_SPECIFIC_USER_PROFILE_DIALOG';
export const HIDE_SPECIFIC_USER_PROFILE_DIALOG = 'HIDE_SPECIFIC_USER_PROFILE_DIALOG';
export const HIDE_EDIT_USER_PROFILE_DIALOG = 'HIDE_EDIT_USER_PROFILE_DIALOG';
export const SHOW_EDIT_USER_PROFILE_DIALOG = 'SHOW_EDIT_USER_PROFILE_DIALOG';
export const SHOW_SEND_MAIL_DIALOG = 'SHOW_SEND_MAIL_DIALOG';
export const HIDE_SEND_MAIL_DIALOG = 'HIDE_SEND_MAIL_DIALOG';

export const SAVE_HISTORY = 'SAVE_HISTORY';
